/**
 * IDLMS - Shared Central Mock Data Repository
 */

const IDLMS_BOOKS = {
    'computer-networks': {
        id: 'computer-networks',
        title: 'Computer Networking',
        subtitle: 'A Top-Down Approach',
        typeBadge: 'Book',
        author: 'James F. Kurose',
        coAuthor: 'Keith W. Ross',
        rating: 4.6,
        ratingCount: '1,245 ratings',
        reviewCount: 1245,
        availability: 'Available',
        statusType: 'available', // available | due-soon | unavailable
        copiesAvailable: 6,
        totalCopies: 12,
        branch: 'Central Library',
        shelf: 'Shelf 3',
        rack: 'R2 – Networking',
        edition: '8th Edition',
        publisher: 'Pearson Education',
        publicationYear: '2021',
        language: 'English',
        subjectCategory: 'Computer Science / Networking',
        about: 'This bestselling text provides a comprehensive introduction to computer networking through the innovative top-down approach. It balances theory and practice with real-world examples, making complex concepts easy to understand. The 8th Edition includes updated coverage of wireless, mobile, and cloud networking, along with new exercises and review questions.',
        aboutExtended: 'Widely adopted by academic institutions and networking professionals worldwide, this edition incorporates recent advancements in networking architecture, Software-Defined Networking (SDN), internet security, and modern transport layer protocols including QUIC. Features hands-on Wireshark lab assignments and comprehensive end-of-chapter problems.',
        cover: 'assets/images/covers/computer-networking.svg',
        dueDate: '28 May 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: [
            'data-communications',
            'tcp-ip-illustrated',
            'wireless-communications',
            'network-security',
            'operating-system-concepts'
        ],
        reviews: [
            {
                author: 'Alex Chen',
                initials: 'AC',
                rating: 5,
                date: '18 May 2025',
                verified: true,
                title: 'The gold standard for networking education',
                comment: "Kurose & Ross's top-down approach makes grasping network layers intuitive and practical. Starting from the Application layer down to the Physical layer matches how modern software engineers actually interact with network systems."
            },
            {
                author: 'Sarah Jenkins',
                initials: 'SJ',
                rating: 4,
                date: '12 May 2025',
                verified: true,
                title: 'Thorough, clear and up-to-date with 5G and Cloud',
                comment: 'The 8th edition updates covering cloud datacenters, 5G cellular systems, and CDN video streaming make this textbook indispensable for any serious CS undergraduate.'
            },
            {
                author: 'Rohan Sharma',
                initials: 'RS',
                rating: 5,
                date: '02 May 2025',
                verified: true,
                title: 'Helped me ace my exams and technical interviews',
                comment: 'Crystal clear explanations of TCP congestion control algorithms, BGP routing, and socket programming with Python.'
            }
        ]
    },

    'data-communications': {
        id: 'data-communications',
        title: 'Data Communications and Networking',
        subtitle: 'With TCP/IP Protocol Suite',
        typeBadge: 'Book',
        author: 'Behrouz A. Forouzan',
        coAuthor: '',
        rating: 4.5,
        ratingCount: '892 ratings',
        reviewCount: 892,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 4,
        totalCopies: 8,
        branch: 'Main Library - 2nd Floor',
        shelf: 'Shelf 2',
        rack: 'TK5105.5 .S73 2017',
        edition: '5th Edition',
        publisher: 'McGraw-Hill Education',
        publicationYear: '2017',
        language: 'English',
        subjectCategory: 'Computer Science / Data Communications',
        about: 'Comprehensive coverage of data communication principles, modern networking technologies, and protocol architectures. Uses visual diagrams to present complex signal encoding, multiplexing, and error detection concepts.',
        aboutExtended: 'Designed for both introductory and advanced courses, Forouzan presents both theoretical foundations and practical applications in standard protocols.',
        cover: 'assets/images/covers/data-comm.svg',
        dueDate: '04 Jun 2025',
        hasPhysical: true,
        hasDigital: false,
        relatedBookIds: ['computer-networks', 'tcp-ip-illustrated', 'network-security'],
        reviews: [
            {
                author: 'David Miller',
                initials: 'DM',
                rating: 5,
                date: '10 May 2025',
                verified: true,
                title: 'Extremely clear diagrams',
                comment: 'Best textbook for visual learners who need to understand physical transmission and data link layer framing.'
            }
        ]
    },

    'tcp-ip-illustrated': {
        id: 'tcp-ip-illustrated',
        title: 'TCP/IP Illustrated, Volume 1',
        subtitle: 'The Protocols',
        typeBadge: 'E-Book',
        author: 'W. Richard Stevens',
        coAuthor: 'Kevin R. Fall',
        rating: 4.6,
        ratingCount: '1,103 ratings',
        reviewCount: 1103,
        availability: 'Available Now',
        statusType: 'available',
        copiesAvailable: 25,
        totalCopies: 25,
        branch: 'Digital Library',
        shelf: 'Digital Cloud Storage',
        rack: 'Online Resource',
        edition: '2nd Edition',
        publisher: 'Addison-Wesley Professional',
        publicationYear: '2011',
        language: 'English',
        subjectCategory: 'Computer Science / Network Protocols',
        about: 'The classic, in-depth guide to TCP/IP protocols and architecture. Examines real packet captures and explains the exact implementation of the Internet protocol suite.',
        aboutExtended: 'Stevens & Fall provide unparalleled insight into IP, ICMP, TCP, UDP, ARP, and routing algorithms with deep packet inspection analysis.',
        cover: 'assets/images/covers/tcp-ip-illustrated.svg',
        dueDate: 'Always Available (Digital)',
        hasPhysical: false,
        hasDigital: true,
        relatedBookIds: ['computer-networks', 'data-communications', 'network-security'],
        reviews: [
            {
                author: 'Elena Rostova',
                initials: 'ER',
                rating: 5,
                date: '15 Apr 2025',
                verified: true,
                title: 'Timeless masterpiece',
                comment: 'Every network engineer and systems architect must have this on their digital shelf.'
            }
        ]
    },

    'wireless-communications': {
        id: 'wireless-communications',
        title: 'Wireless Communications',
        subtitle: 'Principles and Practice',
        typeBadge: 'Book',
        author: 'Andrea Goldsmith',
        coAuthor: '',
        rating: 4.4,
        ratingCount: '654 ratings',
        reviewCount: 654,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 3,
        totalCopies: 6,
        branch: 'Central Library',
        shelf: 'Shelf 4',
        rack: 'R4 – Wireless',
        edition: '1st Edition',
        publisher: 'Cambridge University Press',
        publicationYear: '2018',
        language: 'English',
        subjectCategory: 'Telecommunications / Wireless Networks',
        about: 'A comprehensive introduction to wireless communications, covering cellular systems, fading channels, MIMO systems, and capacity of wireless channels.',
        aboutExtended: 'Written by a world leader in wireless communications, combining mathematical rigor with clear engineering insights.',
        cover: 'assets/images/covers/wireless-comm.svg',
        dueDate: '15 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['computer-networks', 'data-communications', 'network-security'],
        reviews: [
            {
                author: 'Marcus Vance',
                initials: 'MV',
                rating: 5,
                date: '20 Apr 2025',
                verified: true,
                title: 'Rigorous and foundational',
                comment: 'Essential for anyone diving into 5G NR and modern RF signal propagation.'
            }
        ]
    },

    'network-security': {
        id: 'network-security',
        title: 'Network Security Essentials',
        subtitle: 'Applications and Standards',
        typeBadge: 'Book',
        author: 'William Stallings',
        coAuthor: '',
        rating: 4.3,
        ratingCount: '512 ratings',
        reviewCount: 512,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 5,
        totalCopies: 8,
        branch: 'Central Library',
        shelf: 'Shelf 2',
        rack: 'R1 – Security',
        edition: '6th Edition',
        publisher: 'Pearson',
        publicationYear: '2020',
        language: 'English',
        subjectCategory: 'Cybersecurity / Cryptography',
        about: 'A practical survey of network-based and Internet-based security applications and standards, covering symmetric cryptography, public-key encryption, and firewall architectures.',
        aboutExtended: 'Explores practical implementations of IPSec, TLS/SSL, Kerberos, and modern blockchain and zero-trust paradigms.',
        cover: 'assets/images/covers/network-security.svg',
        dueDate: '02 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['computer-networks', 'tcp-ip-illustrated'],
        reviews: [
            {
                author: 'Kavita Nair',
                initials: 'KN',
                rating: 4,
                date: '11 May 2025',
                verified: true,
                title: 'Clear primer on cryptographic standards',
                comment: 'Great explanations of public key infrastructure and web security protocols.'
            }
        ]
    },

    'operating-system-concepts': {
        id: 'operating-system-concepts',
        title: 'Operating System Concepts',
        subtitle: 'Tenth Edition',
        typeBadge: 'Book',
        author: 'Abraham Silberschatz',
        coAuthor: 'Peter B. Galvin, Greg Gagne',
        rating: 4.4,
        ratingCount: '940 ratings',
        reviewCount: 940,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 2,
        totalCopies: 8,
        branch: 'Central Library',
        shelf: 'Shelf 5',
        rack: 'R5 – Systems',
        edition: '10th Edition',
        publisher: 'Wiley',
        publicationYear: '2018',
        language: 'English',
        subjectCategory: 'Computer Science / Systems',
        about: 'The renowned dinosaur book covering operating system architecture, processes, threads, CPU scheduling, synchronization, deadlocks, and virtual memory management.',
        aboutExtended: 'Features updated examples in Linux, Windows 10, and macOS, alongside POSIX programming exercises.',
        cover: 'assets/images/covers/os-concepts.svg',
        dueDate: '30 May 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['computer-networks', 'clean-code'],
        reviews: [
            {
                author: 'Daniel Zhao',
                initials: 'DZ',
                rating: 5,
                date: '28 Apr 2025',
                verified: true,
                title: 'The fundamental OS bible',
                comment: 'Crucial for understanding concurrency and memory paging algorithms.'
            }
        ]
    },

    'ccna-cert-guide': {
        id: 'ccna-cert-guide',
        title: 'CCNA 200-301 Official Cert Guide',
        subtitle: 'Volume 1',
        typeBadge: 'Book',
        author: 'Wendell Odom',
        coAuthor: '',
        rating: 4.6,
        ratingCount: '556 ratings',
        reviewCount: 556,
        availability: 'Due Soon',
        statusType: 'due-soon',
        copiesAvailable: 0,
        totalCopies: 4,
        branch: 'Main Library – 3rd Floor',
        shelf: 'Shelf 1',
        rack: 'TK7871 .O36 2020',
        edition: '1st Edition',
        publisher: 'Cisco Press',
        publicationYear: '2020',
        language: 'English',
        subjectCategory: 'Certifications / Networking',
        about: 'Complete preparation for the CCNA 200-301 exam with real-world examples, hands-on lab exercises, and Pearson test preparation software.',
        aboutExtended: 'Covers networking fundamentals, IP connectivity, IP services, security fundamentals, and network automation.',
        cover: 'assets/images/covers/ccna-cert-guide.svg',
        dueDate: 'Due in 2 days (26 May 2025)',
        hasPhysical: true,
        hasDigital: false,
        relatedBookIds: ['computer-networks', 'tcp-ip-illustrated'],
        reviews: []
    },

    'clean-code': {
        id: 'clean-code',
        title: 'Clean Code',
        subtitle: 'A Handbook of Agile Software Craftsmanship',
        typeBadge: 'Book',
        author: 'Robert C. Martin',
        coAuthor: '',
        rating: 4.7,
        ratingCount: '2,341 ratings',
        reviewCount: 2341,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 3,
        totalCopies: 6,
        branch: 'Central Library',
        shelf: 'Shelf 3',
        rack: 'R6 – Software Engineering',
        edition: '1st Edition',
        publisher: 'Prentice Hall',
        publicationYear: '2008',
        language: 'English',
        subjectCategory: 'Software Engineering',
        about: 'Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Uncle Bob Martin presents revolutionary paradigms for writing readable, maintainable software.',
        aboutExtended: 'Case studies, refactoring walkthroughs, and code smells detection.',
        cover: 'assets/images/covers/clean-code.svg',
        dueDate: '10 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['deep-work', 'operating-system-concepts'],
        reviews: []
    },

    'deep-work': {
        id: 'deep-work',
        title: 'Deep Work',
        subtitle: 'Rules for Focused Success in a Distracted World',
        typeBadge: 'Book',
        author: 'Cal Newport',
        coAuthor: '',
        rating: 4.8,
        ratingCount: '3,120 ratings',
        reviewCount: 3120,
        availability: 'Due Soon',
        statusType: 'due-soon',
        copiesAvailable: 1,
        totalCopies: 5,
        branch: 'Central Library',
        shelf: 'Shelf 1',
        rack: 'R7 – Self-Improvement',
        edition: '1st Edition',
        publisher: 'Grand Central Publishing',
        publicationYear: '2016',
        language: 'English',
        subjectCategory: 'Productivity / Psychology',
        about: 'Deep work is the ability to focus without distraction on a cognitively demanding task. Cal Newport illustrates how cultivating this skill is paramount in an increasingly fragmented digital economy.',
        aboutExtended: 'Actionable strategies for rigorous focus rituals and social media minimization.',
        cover: 'assets/images/covers/deep-work.svg',
        dueDate: '26 May 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['atomic-habits', 'thinking-fast'],
        reviews: []
    },

    'thinking-fast': {
        id: 'thinking-fast',
        title: 'Thinking, Fast and Slow',
        subtitle: 'Two Systems of the Human Mind',
        typeBadge: 'Book',
        author: 'Daniel Kahneman',
        coAuthor: '',
        rating: 4.6,
        ratingCount: '4,210 ratings',
        reviewCount: 4210,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 2,
        totalCopies: 5,
        branch: 'Central Library',
        shelf: 'Shelf 2',
        rack: 'R7 – Behavioral Economics',
        edition: '1st Edition',
        publisher: 'Farrar, Straus and Giroux',
        publicationYear: '2011',
        language: 'English',
        subjectCategory: 'Psychology / Decision Making',
        about: 'Nobel laureate Daniel Kahneman explores the two systems that drive the way we think: System 1 is fast, intuitive, and emotional; System 2 is slower, more deliberative, and more logical.',
        aboutExtended: 'Masterful examination of heuristics, cognitive biases, loss aversion, and prospect theory.',
        cover: 'assets/images/covers/thinking-fast.svg',
        dueDate: '30 May 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['deep-work', 'atomic-habits'],
        reviews: []
    },

    'atomic-habits': {
        id: 'atomic-habits',
        title: 'Atomic Habits',
        subtitle: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones',
        typeBadge: 'Book',
        author: 'James Clear',
        coAuthor: '',
        rating: 4.9,
        ratingCount: '5,430 ratings',
        reviewCount: 5430,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 5,
        totalCopies: 9,
        branch: 'Central Library',
        shelf: 'Shelf 3',
        rack: 'R7 – Self-Improvement',
        edition: '1st Edition',
        publisher: 'Avery / Penguin Random House',
        publicationYear: '2018',
        language: 'English',
        subjectCategory: 'Productivity / Personal Growth',
        about: 'No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear reveals practical strategies on how minute changes can yield transformative results.',
        aboutExtended: 'Four Laws of Behavior Change: Make it obvious, attractive, easy, and satisfying.',
        cover: 'assets/images/covers/atomic-habits.svg',
        dueDate: '08 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['deep-work', 'thinking-fast'],
        reviews: []
    },

    'seven-habits': {
        id: 'seven-habits',
        title: 'The 7 Habits of Highly Effective People',
        subtitle: 'Powerful Lessons in Personal Change',
        typeBadge: 'Book',
        author: 'Stephen R. Covey',
        coAuthor: '',
        rating: 4.8,
        ratingCount: '3,890 ratings',
        reviewCount: 3890,
        availability: 'Due Soon',
        statusType: 'due-soon',
        copiesAvailable: 1,
        totalCopies: 6,
        branch: 'Central Library',
        shelf: 'Shelf 2',
        rack: 'R7 – Self-Improvement',
        edition: '30th Anniversary Edition',
        publisher: 'Simon & Schuster',
        publicationYear: '2020',
        language: 'English',
        subjectCategory: 'Productivity / Leadership',
        about: 'One of the most inspiring and impactful books ever written, The 7 Habits of Highly Effective People has captivated readers for 30 years with its principle-centered approach for solving personal and professional problems.',
        aboutExtended: 'Presents a holistic, integrated, principle-centered approach for solving personal and professional problems with penetrating insights and pointed anecdotes.',
        cover: 'assets/images/covers/seven-habits.svg',
        dueDate: '27 May 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['atomic-habits', 'deep-work', 'thinking-fast'],
        reviews: []
    },

    'sapiens': {
        id: 'sapiens',
        title: 'Sapiens: A Brief History of Humankind',
        subtitle: 'A Brief History of Humankind',
        typeBadge: 'Book',
        author: 'Yuval Noah Harari',
        coAuthor: '',
        rating: 4.7,
        ratingCount: '4,890 ratings',
        reviewCount: 4890,
        availability: 'Overdue',
        statusType: 'unavailable',
        copiesAvailable: 0,
        totalCopies: 7,
        branch: 'Central Library',
        shelf: 'Shelf 1',
        rack: 'R8 – History',
        edition: '1st Edition',
        publisher: 'Harper',
        publicationYear: '2015',
        language: 'English',
        subjectCategory: 'Anthropology / World History',
        about: 'From a renowned historian comes a groundbreaking narrative of humanity’s creation and evolution—exploring the ways in which biology and history have defined us and enhanced our understanding of what it means to be human.',
        aboutExtended: 'Integrating history and science, Harari charts how the Cognitive, Agricultural, and Scientific Revolutions reshaped human society.',
        cover: 'assets/images/covers/sapiens.svg',
        dueDate: '26 May 2025 (Overdue)',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['thinking-fast', 'atomic-habits'],
        reviews: []
    },

    'mindset': {
        id: 'mindset',
        title: 'Mindset: The New Psychology of Success',
        subtitle: 'The New Psychology of Success',
        typeBadge: 'Book',
        author: 'Carol S. Dweck',
        coAuthor: '',
        rating: 4.6,
        ratingCount: '2,940 ratings',
        reviewCount: 2940,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 3,
        totalCopies: 5,
        branch: 'Central Library',
        shelf: 'Shelf 3',
        rack: 'R7 – Psychology',
        edition: 'Updated Edition',
        publisher: 'Ballantine Books',
        publicationYear: '2016',
        language: 'English',
        subjectCategory: 'Psychology / Personal Growth',
        about: 'World-renowned Stanford University psychologist Carol S. Dweck, Ph.D., discovered a simple but groundbreaking idea: the power of mindset. She shows how success in school, work, sports, and the arts can be dramatically influenced by how we think about our talents and abilities.',
        aboutExtended: 'Learn how a growth mindset can motivate those you lead, teach, and love—to transform their lives and your own.',
        cover: 'assets/images/covers/mindset.svg',
        dueDate: '29 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['atomic-habits', 'deep-work'],
        reviews: []
    },

    'psychology-of-money': {
        id: 'psychology-of-money',
        title: 'The Psychology of Money',
        subtitle: 'Timeless lessons on wealth, greed, and happiness',
        typeBadge: 'Book',
        author: 'Morgan Housel',
        coAuthor: '',
        rating: 4.7,
        ratingCount: '3,410 ratings',
        reviewCount: 3410,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 4,
        totalCopies: 8,
        branch: 'Central Library',
        shelf: 'Shelf 4',
        rack: 'R9 – Economics',
        edition: '1st Edition',
        publisher: 'Harriman House',
        publicationYear: '2020',
        language: 'English',
        subjectCategory: 'Finance / Behavioral Economics',
        about: 'Doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. Morgan Housel shares 19 short stories exploring the strange ways people think about money.',
        aboutExtended: 'Essential wisdom on risk, patience, compound interest, and financial independence.',
        cover: 'assets/images/covers/psychology-of-money.svg',
        dueDate: '18 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['atomic-habits', 'thinking-fast'],
        reviews: []
    },

    'computer-networks-internets': {
        id: 'computer-networks-internets',
        title: 'Computer Networks and Internets',
        subtitle: 'With Internet Applications',
        typeBadge: 'Book',
        author: 'Douglas E. Comer',
        coAuthor: '',
        rating: 4.5,
        ratingCount: '620 ratings',
        reviewCount: 620,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 3,
        totalCopies: 5,
        branch: 'Central Library',
        shelf: 'Shelf 3',
        rack: 'R2 – Networking',
        edition: '6th Edition',
        publisher: 'Pearson',
        publicationYear: '2015',
        language: 'English',
        subjectCategory: 'Computer Science / Networking',
        about: 'Offers a comprehensive, self-contained tour through network and Internet technologies from local area networks and packet switching to application protocols.',
        aboutExtended: 'Comer details the technologies that make the Internet work, explaining both hardware and software aspects clearly.',
        cover: 'assets/images/covers/computer-networks-internets.svg',
        dueDate: '14 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['computer-networks', 'tcp-ip-illustrated'],
        reviews: []
    },

    'subtle-art': {
        id: 'subtle-art',
        title: 'The Subtle Art of Not Giving a F*ck',
        subtitle: 'A Counterintuitive Approach to Living a Good Life',
        typeBadge: 'Book',
        author: 'Mark Manson',
        coAuthor: '',
        rating: 4.4,
        ratingCount: '4,150 ratings',
        reviewCount: 4150,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 4,
        totalCopies: 7,
        branch: 'Central Library',
        shelf: 'Shelf 2',
        rack: 'R7 – Self-Improvement',
        edition: '1st Edition',
        publisher: 'HarperOne',
        publicationYear: '2016',
        language: 'English',
        subjectCategory: 'Self-Help / Psychology',
        about: 'In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be "positive" all the time so that we can truly become better, happier people.',
        aboutExtended: 'Manson advises us to get to know our limitations and accept them. Once we embrace our fears, faults, and uncertainties, we can begin to find the courage and honesty we seek.',
        cover: 'assets/images/covers/subtle-art.svg',
        dueDate: '22 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['atomic-habits', 'thinking-fast', 'mindset'],
        reviews: []
    },

    'power-of-habit': {
        id: 'power-of-habit',
        title: 'The Power of Habit',
        subtitle: 'Why We Do What We Do in Life and Business',
        typeBadge: 'Book',
        author: 'Charles Duhigg',
        coAuthor: '',
        rating: 4.5,
        ratingCount: '3,820 ratings',
        reviewCount: 3820,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 3,
        totalCopies: 6,
        branch: 'Central Library',
        shelf: 'Shelf 2',
        rack: 'R7 – Self-Improvement',
        edition: '1st Edition',
        publisher: 'Random House',
        publicationYear: '2012',
        language: 'English',
        subjectCategory: 'Psychology / Personal Growth',
        about: 'Award-winning business reporter Charles Duhigg takes us to the thrilling edge of scientific discoveries that explain why habits exist and how they can be changed.',
        aboutExtended: 'At its core, The Power of Habit contains an exhilarating argument: The key to exercising regularly, losing weight, being more productive, and achieving success is understanding how habits work.',
        cover: 'assets/images/covers/power-of-habit.svg',
        dueDate: '15 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['atomic-habits', 'mindset', 'thinking-fast'],
        reviews: []
    },

    'project-hail-mary': {
        id: 'project-hail-mary',
        title: 'Project Hail Mary',
        subtitle: 'A Novel',
        typeBadge: 'Book',
        author: 'Andy Weir',
        coAuthor: '',
        rating: 4.9,
        ratingCount: '6,210 ratings',
        reviewCount: 6210,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 5,
        totalCopies: 8,
        branch: 'Central Library',
        shelf: 'Shelf 6',
        rack: 'R10 – Fiction',
        edition: '1st Edition',
        publisher: 'Ballantine Books',
        publicationYear: '2021',
        language: 'English',
        subjectCategory: 'Science Fiction / Space Exploration',
        about: 'Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself are doomed.',
        aboutExtended: 'An interstellar adventure of scientific ingenuity, survival, and an unforgettable friendship that spans across light years.',
        cover: 'assets/images/covers/project-hail-mary.svg',
        dueDate: '20 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['clean-code', 'deep-work'],
        reviews: []
    },

    'lessons-in-chemistry': {
        id: 'lessons-in-chemistry',
        title: 'Lessons in Chemistry',
        subtitle: 'A Novel',
        typeBadge: 'Book',
        author: 'Bonnie Garmus',
        coAuthor: '',
        rating: 4.6,
        ratingCount: '4,500 ratings',
        reviewCount: 4500,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 4,
        totalCopies: 6,
        branch: 'Central Library',
        shelf: 'Shelf 6',
        rack: 'R10 – Fiction',
        edition: '1st Edition',
        publisher: 'Doubleday',
        publicationYear: '2022',
        language: 'English',
        subjectCategory: 'Fiction / Historical',
        about: 'Chemist Elizabeth Zott is not your average woman. In fact, Elizabeth Zott would be the first to point out that there is no such thing as an average woman.',
        aboutExtended: 'Set in 1960s California, Elizabeth becomes the reluctant star of America’s most beloved cooking show Supper at Six, teaching a nation of overlooked housewives that the status quo is change-able.',
        cover: 'assets/images/covers/lessons-in-chemistry.svg',
        dueDate: '12 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['midnight-library', 'mindset'],
        reviews: []
    },

    'midnight-library': {
        id: 'midnight-library',
        title: 'The Midnight Library',
        subtitle: 'A Novel',
        typeBadge: 'Book',
        author: 'Matt Haig',
        coAuthor: '',
        rating: 4.5,
        ratingCount: '5,120 ratings',
        reviewCount: 5120,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 3,
        totalCopies: 7,
        branch: 'Central Library',
        shelf: 'Shelf 6',
        rack: 'R10 – Fiction',
        edition: '1st Edition',
        publisher: 'Viking',
        publicationYear: '2020',
        language: 'English',
        subjectCategory: 'Fiction / Fantasy',
        about: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.',
        aboutExtended: 'Nora Seed finds herself faced with the possibility of changing her life for a new one, following a different career, undoing old breakups, realizing her dreams of becoming a glaciologist.',
        cover: 'assets/images/covers/midnight-library.svg',
        dueDate: '17 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['lessons-in-chemistry', 'thinking-fast'],
        reviews: []
    },

    'anxious-generation': {
        id: 'anxious-generation',
        title: 'The Anxious Generation',
        subtitle: 'How the Great Rewiring of Childhood Is Causing an Epidemic of Mental Illness',
        typeBadge: 'Book',
        author: 'Jonathan Haidt',
        coAuthor: '',
        rating: 4.7,
        ratingCount: '2,890 ratings',
        reviewCount: 2890,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 4,
        totalCopies: 6,
        branch: 'Central Library',
        shelf: 'Shelf 2',
        rack: 'R7 – Psychology',
        edition: '1st Edition',
        publisher: 'Penguin Press',
        publicationYear: '2024',
        language: 'English',
        subjectCategory: 'Sociology / Youth & Technology',
        about: 'Social psychologist Jonathan Haidt lays out the facts about the epidemic of teen mental illness and the collapse of play-based childhood in an era of smartphones.',
        aboutExtended: 'Offers concrete, research-backed remedies for parents, teachers, and society to restore healthy human development.',
        cover: 'assets/images/covers/anxious-generation.svg',
        dueDate: '25 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['deep-work', 'mindset', 'atomic-habits'],
        reviews: []
    },

    'build': {
        id: 'build',
        title: 'Build: An Unorthodox Guide to Making Things Worth Making',
        subtitle: 'An Unorthodox Guide to Making Things Worth Making',
        typeBadge: 'Book',
        author: 'Tony Fadell',
        coAuthor: '',
        rating: 4.6,
        ratingCount: '1,920 ratings',
        reviewCount: 1920,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 2,
        totalCopies: 5,
        branch: 'Central Library',
        shelf: 'Shelf 3',
        rack: 'R6 – Software & Product',
        edition: '1st Edition',
        publisher: 'Harper Business',
        publicationYear: '2022',
        language: 'English',
        subjectCategory: 'Business / Product Design',
        about: 'Tony Fadell led the teams that created the iPod, iPhone and Nest thermostat. He offers an advice encyclopedia for anyone who wants to grow, lead, and make something extraordinary.',
        aboutExtended: 'A masterclass in product design, managing teams, navigating startups, and building generational products.',
        cover: 'assets/images/covers/build.svg',
        dueDate: '05 Jun 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['clean-code', 'deep-work'],
        reviews: []
    },

    'the-7-habits': {
        id: 'the-7-habits',
        title: 'The 7 Habits of Highly Effective People',
        subtitle: 'Powerful Lessons in Personal Change',
        typeBadge: 'Book',
        author: 'Stephen R. Covey',
        coAuthor: '',
        rating: 4.8,
        ratingCount: '4,520 ratings',
        reviewCount: 4520,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 3,
        totalCopies: 8,
        branch: 'Central Library',
        shelf: 'Shelf 1',
        rack: 'R4 – Leadership & Self-Help',
        edition: '30th Anniversary Edition',
        publisher: 'Simon & Schuster',
        publicationYear: '2020',
        language: 'English',
        subjectCategory: 'Self-Improvement / Leadership',
        about: 'One of the most inspiring and impactful books ever written, The 7 Habits of Highly Effective People has captivated readers for 30 years with its principle-centered approach for solving personal and professional problems.',
        aboutExtended: 'With penetrating insights and practical anecdotes, Stephen R. Covey reveals a step-by-step pathway for living with fairness, integrity, service, and human dignity—principles that give us the security to adapt to change and the wisdom to take advantage of the opportunities that change creates.',
        cover: 'assets/images/covers/seven-habits.svg',
        dueDate: '15 May 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['atomic-habits', 'deep-work', 'mindset'],
        reviews: []
    },

    'seven-habits': {
        id: 'seven-habits',
        title: 'The 7 Habits of Highly Effective People',
        subtitle: 'Powerful Lessons in Personal Change',
        typeBadge: 'Book',
        author: 'Stephen R. Covey',
        coAuthor: '',
        rating: 4.8,
        ratingCount: '4,520 ratings',
        reviewCount: 4520,
        availability: 'Available',
        statusType: 'available',
        copiesAvailable: 3,
        totalCopies: 8,
        branch: 'Central Library',
        shelf: 'Shelf 1',
        rack: 'R4 – Leadership & Self-Help',
        edition: '30th Anniversary Edition',
        publisher: 'Simon & Schuster',
        publicationYear: '2020',
        language: 'English',
        subjectCategory: 'Self-Improvement / Leadership',
        about: 'One of the most inspiring and impactful books ever written, The 7 Habits of Highly Effective People has captivated readers for 30 years with its principle-centered approach for solving personal and professional problems.',
        aboutExtended: 'With penetrating insights and practical anecdotes, Stephen R. Covey reveals a step-by-step pathway for living with fairness, integrity, service, and human dignity—principles that give us the security to adapt to change and the wisdom to take advantage of the opportunities that change creates.',
        cover: 'assets/images/covers/seven-habits.svg',
        dueDate: '15 May 2025',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['atomic-habits', 'deep-work', 'mindset'],
        reviews: []
    },

    'artificial-intelligence': {
        id: 'artificial-intelligence',
        title: 'Artificial Intelligence: A Modern Approach',
        subtitle: 'Global Edition (4th Edition)',
        typeBadge: 'E-Book',
        author: 'Stuart Russell',
        coAuthor: 'Peter Norvig',
        rating: 4.8,
        ratingCount: '3,840 ratings',
        reviewCount: 3840,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'AI / Machine Learning',
        edition: '4th Edition',
        publisher: 'Pearson',
        publicationYear: '2021',
        language: 'English',
        subjectCategory: 'Computer Science / Artificial Intelligence',
        about: 'The leading textbook in Artificial Intelligence, used in over 1,500 universities across 135 countries. Explores unified approaches to intelligent agents, probabilistic reasoning, machine learning, and deep learning.',
        aboutExtended: 'This 4th edition expands coverage of deep learning, probabilistic programming, multiagent systems, machine learning ethics, fairness, and safety in autonomous systems.',
        cover: 'assets/images/covers/ai-modern-approach.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['machine-learning-mitchell', 'deep-learning-goodfellow', 'computer-networks'],
        reviews: []
    },

    'database-system-concepts': {
        id: 'database-system-concepts',
        title: 'Database System Concepts',
        subtitle: '7th Edition',
        typeBadge: 'E-Book',
        author: 'Abraham Silberschatz',
        coAuthor: 'Henry F. Korth, S. Sudarshan',
        rating: 4.7,
        ratingCount: '2,410 ratings',
        reviewCount: 2410,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'Database Systems',
        edition: '7th Edition',
        publisher: 'McGraw-Hill',
        publicationYear: '2020',
        language: 'English',
        subjectCategory: 'Computer Science / Databases',
        about: 'Presents the fundamental concepts of database management in an intuitive manner, including relational model, SQL, transactions, concurrency control, and distributed storage systems.',
        aboutExtended: 'Features updated material on modern Big Data architectures, NoSQL databases, columnar stores, cloud databases, and blockchain storage.',
        cover: 'assets/images/covers/database-system-concepts.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['operating-system-concepts', 'computer-networks'],
        reviews: []
    },

    'algorithms-cormen': {
        id: 'algorithms-cormen',
        title: 'Design and Analysis of Algorithms',
        subtitle: 'Introduction to Algorithms (4th Edition)',
        typeBadge: 'PDF',
        author: 'Thomas H. Cormen',
        coAuthor: 'Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
        rating: 4.9,
        ratingCount: '6,210 ratings',
        reviewCount: 6210,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'Algorithms & Data Structures',
        edition: '4th Edition',
        publisher: 'MIT Press',
        publicationYear: '2022',
        language: 'English',
        subjectCategory: 'Computer Science / Algorithms',
        about: 'Comprehensive and rigorous reference textbook on modern algorithms. Covers divide-and-conquer, dynamic programming, greedy algorithms, graph algorithms, and NP-completeness.',
        aboutExtended: 'Written in clear pseudo-code accessible to all levels of computer science readers, with mathematical explanations and extensive analysis.',
        cover: 'assets/images/covers/algorithms-cormen.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['data-structures-weiss', 'clean-code'],
        reviews: []
    },

    'machine-learning-mitchell': {
        id: 'machine-learning-mitchell',
        title: 'Machine Learning Basics',
        subtitle: 'Core Foundations & Algorithms',
        typeBadge: 'E-Book',
        author: 'Tom M. Mitchell',
        coAuthor: '',
        rating: 4.6,
        ratingCount: '1,890 ratings',
        reviewCount: 1890,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'AI / Machine Learning',
        edition: '1st Edition',
        publisher: 'McGraw-Hill',
        publicationYear: '2019',
        language: 'English',
        subjectCategory: 'Computer Science / Machine Learning',
        about: 'Clear baseline foundation for computer science students to master supervised learning, decision trees, neural networks, Bayesian learning, and reinforcement learning.',
        aboutExtended: 'Connects core statistical principles to software implementation in modern programming environments.',
        cover: 'assets/images/covers/machine-learning-mitchell.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['artificial-intelligence', 'deep-learning-goodfellow'],
        reviews: []
    },

    'data-structures-weiss': {
        id: 'data-structures-weiss',
        title: 'Data Structures and Algorithm Analysis in C++',
        subtitle: '4th Edition',
        typeBadge: 'PDF',
        author: 'Mark Allen Weiss',
        coAuthor: '',
        rating: 4.7,
        ratingCount: '1,530 ratings',
        reviewCount: 1530,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'Algorithms & Data Structures',
        edition: '4th Edition',
        publisher: 'Pearson',
        publicationYear: '2020',
        language: 'English',
        subjectCategory: 'Computer Science / Programming',
        about: 'Provides an advanced approach to data structures and algorithm analysis using modern C++. Covers trees, heaps, sorting, graphs, and amortized complexity.',
        aboutExtended: 'Includes practical code examples utilizing C++ templates, STL, and memory management best practices.',
        cover: 'assets/images/covers/data-structures-weiss.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['algorithms-cormen', 'clean-code'],
        reviews: []
    },

    'python-crash-course': {
        id: 'python-crash-course',
        title: 'Python Crash Course 3rd Edition',
        subtitle: 'A Hands-On, Project-Based Introduction to Programming',
        typeBadge: 'E-Book',
        author: 'Eric Matthes',
        coAuthor: '',
        rating: 4.6,
        ratingCount: '1,200 ratings',
        reviewCount: 1200,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'Software Engineering',
        edition: '3rd Edition',
        publisher: 'No Starch Press',
        publicationYear: '2023',
        language: 'English',
        subjectCategory: 'Computer Science / Python',
        about: 'Fast-paced, thorough introduction to Python that will have you writing programs, solving problems, and making things that work in no time.',
        aboutExtended: 'Includes projects building 2D space invasion arcade games, data visualizations with Matplotlib, and web applications with Django.',
        cover: 'assets/images/covers/python-crash-course.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['clean-code', 'pragmatic-programmer'],
        reviews: []
    },

    'deep-learning-goodfellow': {
        id: 'deep-learning-goodfellow',
        title: 'Deep Learning',
        subtitle: 'Adaptive Computation and Machine Learning',
        typeBadge: 'PDF',
        author: 'Ian Goodfellow',
        coAuthor: 'Yoshua Bengio, Aaron Courville',
        rating: 4.7,
        ratingCount: '980 ratings',
        reviewCount: 980,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'AI / Deep Learning',
        edition: '1st Edition',
        publisher: 'MIT Press',
        publicationYear: '2016',
        language: 'English',
        subjectCategory: 'Computer Science / Deep Learning',
        about: 'The definitive textbook on deep learning covering mathematical fundamentals, convolutional networks, sequence modeling, autoencoders, and generative models.',
        aboutExtended: 'Widely praised by Elon Musk, Demis Hassabis, and Geoffrey Hinton as the benchmark textbook for the AI revolution.',
        cover: 'assets/images/covers/deep-learning-goodfellow.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['artificial-intelligence', 'machine-learning-mitchell'],
        reviews: []
    },

    'pragmatic-programmer': {
        id: 'pragmatic-programmer',
        title: 'The Pragmatic Programmer',
        subtitle: '20th Anniversary Edition: Your Journey to Mastery',
        typeBadge: 'E-Book',
        author: 'David Thomas',
        coAuthor: 'Andrew Hunt',
        rating: 4.7,
        ratingCount: '890 ratings',
        reviewCount: 890,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'Software Engineering',
        edition: '20th Anniversary Edition',
        publisher: 'Addison-Wesley',
        publicationYear: '2019',
        language: 'English',
        subjectCategory: 'Software Engineering / Career',
        about: 'One of the most significant books on software engineering, teaching practical tips to craft maintainable code, test thoroughly, and excel as an engineer.',
        aboutExtended: 'Updated for modern engineering practices, distributed systems, concurrency, and team communication.',
        cover: 'assets/images/covers/pragmatic-programmer.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['clean-code', 'software-engineering-pressman'],
        reviews: []
    },

    'discrete-math-rosen': {
        id: 'discrete-math-rosen',
        title: 'Discrete Mathematics and Its Applications',
        subtitle: '8th Edition',
        typeBadge: 'E-Book',
        author: 'Kenneth H. Rosen',
        coAuthor: '',
        rating: 4.5,
        ratingCount: '760 ratings',
        reviewCount: 760,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'Mathematics',
        edition: '8th Edition',
        publisher: 'McGraw-Hill',
        publicationYear: '2019',
        language: 'English',
        subjectCategory: 'Mathematics / Discrete Math',
        about: 'Standard university textbook for discrete structures, boolean algebra, logic, combinatorics, discrete probability, graph theory, and automata theory.',
        aboutExtended: 'Packed with practical applications in algorithm complexity, computer security, network routing, and data structures.',
        cover: 'assets/images/covers/discrete-math-rosen.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['theory-computation-sipser', 'algorithms-cormen'],
        reviews: []
    },

    'theory-computation-sipser': {
        id: 'theory-computation-sipser',
        title: 'Theory of Computation',
        subtitle: 'Introduction to the Theory of Computation (3rd Edition)',
        typeBadge: 'PDF',
        author: 'Michael Sipser',
        coAuthor: '',
        rating: 4.6,
        ratingCount: '540 ratings',
        reviewCount: 540,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'Theoretical Computer Science',
        edition: '3rd Edition',
        publisher: 'Cengage Learning',
        publicationYear: '2013',
        language: 'English',
        subjectCategory: 'Computer Science / Theory',
        about: 'Highly acclaimed text on formal languages, automata, computability, and complexity theory. Known for intuitive explanations and mathematical elegance.',
        aboutExtended: 'Master DFA, NFA, Turing machines, decidability, the Halting Problem, and P vs NP complexity classes.',
        cover: 'assets/images/covers/theory-computation-sipser.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['discrete-math-rosen', 'compiler-design-aho'],
        reviews: []
    },

    'compiler-design-aho': {
        id: 'compiler-design-aho',
        title: 'Compiler Design: Principles, Techniques, and Tools',
        subtitle: 'The Classic Dragon Book (2nd Edition)',
        typeBadge: 'E-Book',
        author: 'Alfred V. Aho',
        coAuthor: 'Monica S. Lam, Ravi Sethi, Jeffrey D. Ullman',
        rating: 4.5,
        ratingCount: '680 ratings',
        reviewCount: 680,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'Compilers & Languages',
        edition: '2nd Edition',
        publisher: 'Pearson',
        publicationYear: '2006',
        language: 'English',
        subjectCategory: 'Computer Science / Compilers',
        about: 'The definitive work on compiler construction, syntax-directed translation, lexical analysis, parsing, intermediate code generation, and runtime systems.',
        aboutExtended: 'Comprehensive coverage of modern code optimization, register allocation, instruction scheduling, and just-in-time compilation.',
        cover: 'assets/images/covers/compiler-design-aho.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['theory-computation-sipser', 'operating-system-concepts'],
        reviews: []
    },

    'software-engineering-pressman': {
        id: 'software-engineering-pressman',
        title: 'Software Engineering: A Practitioner’s Approach',
        subtitle: '9th Edition',
        typeBadge: 'E-Book',
        author: 'Roger S. Pressman',
        coAuthor: 'Bruce R. Maxim',
        rating: 4.4,
        ratingCount: '710 ratings',
        reviewCount: 710,
        availability: 'Instant Digital Access',
        statusType: 'available',
        copiesAvailable: 99,
        totalCopies: 100,
        branch: 'Digital Cloud Repository',
        shelf: 'Digital Cloud',
        rack: 'Software Engineering',
        edition: '9th Edition',
        publisher: 'McGraw-Hill',
        publicationYear: '2020',
        language: 'English',
        subjectCategory: 'Computer Science / Software Engineering',
        about: 'World’s bestselling guide to software engineering, emphasizing agile methods, DevOps, software architecture, quality assurance, and project management.',
        aboutExtended: 'Contains case studies, practical engineering patterns, modern CI/CD pipelines, and software maintenance guidelines.',
        cover: 'assets/images/covers/software-engineering-pressman.svg',
        dueDate: 'Unlimited E-Access',
        hasPhysical: true,
        hasDigital: true,
        relatedBookIds: ['clean-code', 'pragmatic-programmer'],
        reviews: []
    }
};

// Helper to look up a book by id or return the default Computer Networks book
function getBookById(id) {
    if (!id) return IDLMS_BOOKS['computer-networks'];
    const cleanId = id.trim().toLowerCase();
    return IDLMS_BOOKS[cleanId] || IDLMS_BOOKS['computer-networks'];
}
